### ISSUE TITLE
Request get_shop_following not response list data-follower-shop-id

### ISSUE THREAD

**Issue by anhntsi** [bro-11/shopeefollow#1]
Hi friends,

Thank for great tool. I have run it before and it is ok for me.

But now, the tool is have issue about work recursively. Because it isn't get get_shop_following data. I think shopee has change something.

Can you help me to check it?

**Comment by bro-11** [comment]
iya gan, skrng make javascript buat ngeload pagenya.
nanti ane coba fix, terimakasih
